### ISSUE TITLE
Code not compiling and proxy too slow error coming always

### ISSUE THREAD

**Issue by thundercatliono** [JijaProGamer/Youtube-Rumble-View-Bot#29]
When i compile the code using the install.bat file the following errors are reported, please see attached.
[errors.txt](https://github.com/JijaProGamer/Youtube-View-Bot/files/14233984/errors.txt)

Further, even when using proxy from iproyal or local proxy the application is stuck in "check proxy" loop and eventually returns proxy is too slow errors. Please advise.

**Comment by JijaProGamer** [comment]
If you are using iproyal or proxies you 100% are sure won't error, set "skip proxy check" to true.

**Comment by JijaProGamer** [comment]
Fixed first error, second one is getting a fix next major update.
