### ISSUE TITLE
Problem: Proxies Leak IP Address

### ISSUE THREAD

**Issue by Ayaz082** [JijaProGamer/Youtube-Rumble-View-Bot#32]
Hi, There is problem with this, I am using residential proxies but from 4, 5 days its getting problem with
**Problem: Proxy Leak IP address** 

So can you please Fix this issue 
I cant use this because of this error.

I am using node-v18.6.0-x64.

**Comment by Ayaz082** [comment]
![Capture](https://github.com/JijaProGamer/Youtube-Rumble-View-Bot/assets/174582743/610f55d0-f47f-4d75-a273-a1169b50126b)

**Comment by JijaProGamer** [comment]
Will be fixed next version.

Also, please don't send screenshots of your proxies in public, everyone can see them.

**Comment by JijaProGamer** [comment]
Fixed internally, will be pushed out soon.
