### ISSUE TITLE
nothing is working for me 

### ISSUE THREAD

**Issue by lukijosh** [JijaProGamer/Youtube-Rumble-View-Bot#33]
i downloaded every thing but it keeps saying the npm is failing and it keeps kicking me out I'm using a dell laptop idk if that matters but yeah can u please help me

**Comment by lukijosh** [comment]
to comment i have no experience doing this before so i need some help

**Comment by JijaProGamer** [comment]
Did you follow the installation page at https://www.bloxxy.net/projects/2 ? anything not followed correctly (not using the correct nodejs version, not installing extra tools, or using administrator while installing) will not allow it to install correctly

**Comment by lukijosh** [comment]
yes i made sure i followed every single step wrd for wrd and its not working

**Comment by lukijosh** [comment]
you might have to make a video to help because i know i followed every step i just dont know whats going on ieven rested my laptop

**Comment by JijaProGamer** [comment]
If you type "node -v" in a terminal, what does it show? Also, what errors appear while installing?

**Comment by lukijosh** [comment]
when i do that it says Uncaught ReferenceError: Node is not defined and the erro keeps spamminng something about the npm

**Comment by lukiboss123** [comment]
![image](https://github.com/user-attachments/assets/67358154-c223-472e-9bf5-0b6b5ad63d83)



I'm on another acc but this what I see when Instal the bat

**Comment by lukiboss123** [comment]
Then when I try to download the run file it just goes fast then kicks me out do I'm confuse

**Comment by lukiboss123** [comment]
It would be nice if I could get a little bit of help or a visual tut so I can know what to do 😭

**Comment by JijaProGamer** [comment]
> ![image](https://private-user-images.githubusercontent.com/178560133/358789799-67358154-c223-472e-9bf5-0b6b5ad63d83.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NzMzNTksIm5iZiI6MTcyMzg3MzA1OSwicGF0aCI6Ii8xNzg1NjAxMzMvMzU4Nzg5Nzk5LTY3MzU4MTU0LWMyMjMtNDcyZS05YmY1LTBiNmI1YWQ2M2Q4My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDUzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzYyZjlkOWFjNzFmNmQ4NTEyYjI0MmIwMGQxOGEzNGM3MjkwOTc3ZmI4OGU2YTJhZDJhMmVjMjkyZDM2OGUzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5V41Pamakfv61GcCbr_MLe4DA8p9DJMIKY7rwxOoFJM)
> 
> I'm on another acc but this what I see when Instal the bat

That means you didn't actually follow the installation tutorial, since the installation tutorial clearly states that using administrator when installing the bot will corrupt the files and you'll have to reinstall from git and install without administrator

**Comment by lukiboss123** [comment]
That's what I did and it didn't work when I said I was on another account I was talking about the GitHub account

**Comment by JijaProGamer** [comment]
Remove the bot folder, reinstall from GitHub, and run install.bat without administrator

**Comment by lukiboss123** [comment]
After a couple of tries if finally worked thx for the help
