### ISSUE TITLE
After spending hours it running like this

### ISSUE THREAD

**Issue by new2gi** [JijaProGamer/Youtube-Rumble-View-Bot#36]
![Screenshot 2024-08-22 000010](https://github.com/user-attachments/assets/cafdd002-e0ab-4730-a08e-f9d700090fea)

**Comment by new2gi** [comment]
npm warn deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change

**Comment by JijaProGamer** [comment]
What are your specs? Just rerun the installer if it gets stuck, but it never got stuck as of now.

**Comment by JijaProGamer** [comment]
Not a issue
