### ISSUE TITLE
please check this

### ISSUE THREAD

**Issue by new2gi** [JijaProGamer/Youtube-Rumble-View-Bot#37]
I followed instruction 
i ran this **Windows: install.bat**
"npm warn deprecated gar@1.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

up to date, audited 897 packages in 2s

138 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (5 moderate, 11 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

changed 75 packages in 5s

21 packages are looking for funding
  run `npm fund` for details

> youtube-view-bot@1.0.0 build
> vite build

vite v4.5.3 building SSR bundle for production...
transforming (16) ..\node_modules\@sveltejs\kit\src\runtime\server\respond.js12:14:41 am [vite-plugin-svelte] C:/Users/iamja/OneDrive/Desktop/Youtube-Rumble-View-Bot-master/main/src/routes/ReminderMessage.svelte:94:8 A11y: Screenreaders already announce <img> elements as an image.
92:     <div class="message-container">
93:         <h class="message-title">{@html title}</h>
94:         <img class="message-image" src="{image}" alt="Message image">
            ^
95:
96:         {#each text.split("\n") as line}
✓ 120 modules transformed.
12:14:42 am [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

svelte-chartjs@3.1.2
@bulatdashiev/svelte-slider@1.0.3
svelte-multiselect@8.6.2

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.

vite v4.5.3 building for production...
transforming (31) src\routes\+layout.ts12:14:44 am [vite-plugin-svelte] C:/Users/iamja/OneDrive/Desktop/Youtube-Rumble-View-Bot-master/main/src/routes/ReminderMessage.svelte:94:8 A11y: Screenreaders already announce <img> elements as an image.
92:     <div class="message-container">
93:         <h class="message-title">{@html title}</h>
94:         <img class="message-image" src="{image}" alt="Message image">
            ^
95:
96:         {#each text.split("\n") as line}
✓ 195 modules transformed.
.svelte-kit/output/client/_app/version.json                               0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/.vite/manifest.json                             8.31 kB │ gzip:  0.91 kB
.svelte-kit/output/client/_app/immutable/assets/6.d2e8e422.css            0.62 kB │ gzip:  0.32 kB
.svelte-kit/output/client/_app/immutable/assets/Slider.eca6fcd8.css       0.91 kB │ gzip:  0.38 kB
.svelte-kit/output/client/_app/immutable/assets/7.98374c83.css            0.92 kB │ gzip:  0.42 kB
.svelte-kit/output/client/_app/immutable/assets/3.3f5cc4d7.css            0.99 kB │ gzip:  0.43 kB
.svelte-kit/output/client/_app/immutable/assets/all.43394077.css          1.00 kB │ gzip:  0.26 kB
.svelte-kit/output/client/_app/immutable/assets/4.437a20b1.css            1.70 kB │ gzip:  0.61 kB
.svelte-kit/output/client/_app/immutable/assets/8.740208c5.css            1.81 kB │ gzip:  0.63 kB
.svelte-kit/output/client/_app/immutable/assets/2.4a5acf9c.css            2.14 kB │ gzip:  0.63 kB
.svelte-kit/output/client/_app/immutable/assets/9.558da423.css            2.41 kB │ gzip:  0.75 kB
.svelte-kit/output/client/_app/immutable/assets/0.4fd01c49.css            5.40 kB │ gzip:  1.33 kB
.svelte-kit/output/client/_app/immutable/assets/10.4c8c1959.css           7.88 kB │ gzip:  2.02 kB
.svelte-kit/output/client/_app/immutable/nodes/5.c722d816.js              0.25 kB │ gzip:  0.21 kB
.svelte-kit/output/client/_app/immutable/chunks/index.7c7d3ff3.js         0.45 kB │ gzip:  0.31 kB
.svelte-kit/output/client/_app/immutable/nodes/1.51d73da6.js              0.98 kB │ gzip:  0.57 kB
.svelte-kit/output/client/_app/immutable/nodes/6.11135d0c.js              1.80 kB │ gzip:  0.90 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.834bd054.js    2.46 kB │ gzip:  1.27 kB
.svelte-kit/output/client/_app/immutable/nodes/7.5bcf7677.js              3.25 kB │ gzip:  1.49 kB
.svelte-kit/output/client/_app/immutable/nodes/3.c70b835d.js              4.49 kB │ gzip:  1.87 kB
.svelte-kit/output/client/_app/immutable/chunks/all.c7533621.js           7.04 kB │ gzip:  1.86 kB
.svelte-kit/output/client/_app/immutable/chunks/Slider.a39cc87f.js        7.29 kB │ gzip:  2.76 kB
.svelte-kit/output/client/_app/immutable/entry/app.d14133aa.js            7.90 kB │ gzip:  2.72 kB
.svelte-kit/output/client/_app/immutable/nodes/4.e9318c95.js              9.29 kB │ gzip:  3.21 kB
.svelte-kit/output/client/_app/immutable/nodes/8.f39826c6.js              9.84 kB │ gzip:  3.53 kB
.svelte-kit/output/client/_app/immutable/chunks/index.bf524aca.js        14.74 kB │ gzip:  6.06 kB
.svelte-kit/output/client/_app/immutable/nodes/9.59792dc8.js             16.12 kB │ gzip:  5.23 kB
.svelte-kit/output/client/_app/immutable/nodes/0.bc5cf720.js             19.86 kB │ gzip:  6.65 kB
.svelte-kit/output/client/_app/immutable/entry/start.62ce8f94.js         25.31 kB │ gzip:  9.98 kB
.svelte-kit/output/client/_app/immutable/chunks/axios.28bc18a3.js        29.45 kB │ gzip: 11.91 kB
.svelte-kit/output/client/_app/immutable/chunks/background.253e5254.js   40.88 kB │ gzip: 12.96 kB
.svelte-kit/output/client/_app/immutable/nodes/10.a9f1dceb.js            80.43 kB │ gzip: 24.59 kB
.svelte-kit/output/client/_app/immutable/nodes/2.ae32c0c8.js            219.61 kB │ gzip: 75.44 kB
✓ built in 4.52s
.svelte-kit/output/server/.vite/manifest.json                             5.89 kB
.svelte-kit/output/server/_app/immutable/assets/_page.d2e8e422.css        0.62 kB
.svelte-kit/output/server/_app/immutable/assets/Slider.0d8463ab.css       0.89 kB
.svelte-kit/output/server/_app/immutable/assets/_page.98374c83.css        0.92 kB
.svelte-kit/output/server/_app/immutable/assets/_page.3f5cc4d7.css        0.99 kB
.svelte-kit/output/server/_app/immutable/assets/all.43394077.css          1.00 kB
.svelte-kit/output/server/_app/immutable/assets/_page.437a20b1.css        1.70 kB
.svelte-kit/output/server/_app/immutable/assets/_page.740208c5.css        1.81 kB
.svelte-kit/output/server/_app/immutable/assets/_page.4a5acf9c.css        2.14 kB
.svelte-kit/output/server/_app/immutable/assets/_page.558da423.css        2.41 kB
.svelte-kit/output/server/_app/immutable/assets/_layout.4fd01c49.css      5.40 kB
.svelte-kit/output/server/_app/immutable/assets/_page.4c8c1959.css        7.88 kB
.svelte-kit/output/server/entries/pages/_layout.ts.js                     0.08 kB
.svelte-kit/output/server/internal.js                                     0.19 kB
.svelte-kit/output/server/entries/pages/extension/_eid_/_page.svelte.js   0.30 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js               0.89 kB
.svelte-kit/output/server/chunks/index.js                                 1.33 kB
.svelte-kit/output/server/chunks/background.js                            1.56 kB
.svelte-kit/output/server/entries/pages/extensions/_page.svelte.js        1.60 kB
.svelte-kit/output/server/chunks/all.js                                   2.38 kB
.svelte-kit/output/server/entries/pages/login/_page.svelte.js             2.49 kB
.svelte-kit/output/server/entries/pages/change_password/_page.svelte.js   2.96 kB
.svelte-kit/output/server/chunks/Slider.js                                5.00 kB
.svelte-kit/output/server/chunks/internal.js                              5.71 kB
.svelte-kit/output/server/entries/pages/console/_page.svelte.js           5.97 kB
.svelte-kit/output/server/entries/pages/proxies/_page.svelte.js           6.30 kB
.svelte-kit/output/server/chunks/index2.js                                8.48 kB
.svelte-kit/output/server/entries/pages/settings/_page.svelte.js         10.54 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js                  14.49 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                19.22 kB
.svelte-kit/output/server/entries/pages/videos/_page.svelte.js           51.27 kB
.svelte-kit/output/server/index.js                                       91.91 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
"

then this **Windows: run.bat**

**it opens cmd and closes instantly**

**Comment by JijaProGamer** [comment]
What NodeJS version do you have installed, and did you tick the "extra tools" checkbox? You need NodeJS v18 LTS.

**Comment by JijaProGamer** [comment]
closed as no response

**Comment by JijaProGamer** [comment]
.

**Comment by JijaProGamer** [comment]
.
