### ISSUE TITLE
Error navigating to video using "search"

### ISSUE THREAD

**Issue by Etharito** [JijaProGamer/Youtube-Rumble-View-Bot#38]
Hi,
I am getting this error on the CMD when I check when I add search terms.

Error navigating to video using "search": Error: Error: page.waitForNavigation: NS_BINDING_ABORTED; maybe frame was detached?
=========================== logs ===========================
waiting for navigation until "load"
============================================================

Can you check and let me know if there is any fix or am I doing something wrong

**Comment by JijaProGamer** [comment]
That error only appears when you manually close the browser, or your system closed it (anti virus, ram/cpu being used at max, or other apps interfering)

**Comment by Etharito** [comment]
oh ok thanks for letting me know.
